version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_CONNECTION_STRING=mongodb://mongo:27017
      - DB_NAME=inventoryDB
      - API_KEY=your_secure_key
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
